openapi: 3.0.0
info:
  version: 1.0.0
  title: ArcoPrime PIM project API/endpoints
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: contacto@arcoprime.cl
    url: 'https://arcoprime.cl/'
  x-logo:
    url: 'https://www.prontocopec.cl/pronto/site/artic/20170516/imag/foto_0000000320170516112513.png'
    altText: Pronto Copec
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: geography
    description: 'Operations about geography functionalities just like countries, regions, cities and communes info'
  - name: files
    description: 'Operations about files functionalities just like upload, download or update a file'
  - name: users
    description: Operations about system users
  - name: supplier
    description: Operations about suppliers
  - name: product
    description: Operations about products
x-tagGroups:
  - name: General
    tags:
      - supplier
      - product
  - name: File management
    tags:
      - files
  - name: Geo management
    tags:
      - geography
  - name: System management
    tags:
      - users
paths:
  /helpers/country/:
    get:
      tags:
        - geography
      summary: Get countries
      operationId: get-helpers-country
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  '/helpers/country/{id}':
    get:
      tags:
        - geography
      summary: Get one country
      description: Returns a single country
      operationId: get-helpers-one-country
      parameters:
        - name: id
          in: path
          description: ID of country to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetail'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCountryInvalidId'
        '404':
          description: Country not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCountryNotFound'
  /helpers/region:
    get:
      tags:
        - geography
      summary: Get regions
      description: Returns all the regions of one country
      operationId: get-helpers-region
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
        '400':
          description: Invalid country code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRegionInvalidCountryCode'
      parameters:
        - schema:
            type: string
            example: CHL
          in: query
          name: countryCode
  '/helpers/region/{id}':
    get:
      tags:
        - geography
      summary: Get one region
      description: Returns a single region
      operationId: get-helpers-one-region
      parameters:
        - name: id
          in: path
          description: ID of region to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRegionInvalidId'
        '404':
          description: Region not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRegionNotFound'
  /helpers/commune:
    get:
      tags:
        - geography
      summary: Get communes
      description: Returns all the communes of one region
      operationId: get-helpers-commune
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Commune'
        '400':
          description: Invalid region code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCommuneInvalidRegionCode'
      parameters:
        - schema:
            type: number
            example: 2824
          in: query
          name: regionCode
  '/helpers/commune/{id}':
    get:
      tags:
        - geography
      summary: Get one commune
      description: Returns a single commune
      operationId: get-helpers-one-commune
      parameters:
        - name: id
          in: path
          description: ID of commune to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commune'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCommuneInvalidId'
        '404':
          description: Commune not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCommuneNotFound'
  /helpers/city:
    get:
      tags:
        - geography
      summary: Get cities
      description: Returns all the cities of one commune
      operationId: get-helpers-city
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
        '400':
          description: Invalid commune code
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCityInvalidCommuneCode'
      parameters:
        - schema:
            type: number
            example: 295
          in: query
          name: communeCode
  '/helpers/city/{id}':
    get:
      tags:
        - geography
      summary: Get one city
      description: Returns a single city
      operationId: get-helpers-one-city
      parameters:
        - name: id
          in: path
          description: ID of city to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCityInvalidId'
        '404':
          description: City not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorCityNotFound'
  '/helpers/file/{uuid}':
    get:
      tags:
        - files
      summary: Get a file
      description: Returns a uploaded file
      operationId: get-uploaded-file
      parameters:
        - name: uuid
          in: path
          description: UUID of file to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid UUID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorFileInvalidUuid'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnauthorized'
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorFileNotFound'
        '503':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorUnavailable'
        '504':
          description: Gateway timeout
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorTimeout'
    delete:
      tags:
        - files
      summary: Delete a file
      description: Delete a uploaded file
      operationId: delete-uploaded-file
      parameters:
        - name: uuid
          in: path
          description: UUID of file to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid UUID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorFileInvalidUuid'
              examples:
                example-1:
                  value:
                    error: Invalid UUID of file
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorFileNotFound'
        '500':
          description: Internal Server Error
  /helpers/file:
    post:
      tags:
        - files
      summary: Upload a file
      description: Upload a file to the bucket
      operationId: post-upload-file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                domain:
                  type: string
                content:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: cacf2e09-9647-4f84-9d5e-5ddcb37d4cc0
                    description: UUID del archivo
                    format: uuid
                required:
                  - code
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorFileBadRequest'
components:
  schemas:
    Country:
      title: Country
      type: object
      properties:
        id:
          type: number
          description: Id of the country in database
          example: 44
        name:
          type: string
          description: Full country name in spanish language
          example: Chile
        code:
          type: string
          description: ISO standard 3166-1 alfa-3
          example: CHL
        phonePrefix:
          type: string
          description: International phone code of the country
          example: '+56'
    CountryDetail:
      title: Country
      type: object
      properties:
        id:
          type: number
          description: Id of the country in database
          example: 44
        name:
          type: string
          description: Full country name in spanish language
          example: Chile
        nameEn:
          type: string
          description: Full country name in english language
          example: Chile
        code:
          type: string
          description: ISO standard 3166-1 alfa-3
          example: CHL
        phonePrefix:
          type: string
          description: International phone code of the country
          example: '+56'
    ErrorCountryInvalidId:
      title: Invalid id
      type: object
      properties:
        error:
          type: string
          description: Invalid id of country
          example: Invalid id of country
    ErrorCountryNotFound:
      title: Country not found
      type: object
      properties:
        error:
          type: string
          description: Country not found
          example: Country not found
    Region:
      title: Region
      type: object
      properties:
        id:
          type: number
          description: Id of the region in database
          example: 2824
        name:
          type: string
          description: Name of the region in database
          example: Región Metropolitana de Santiago
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    ErrorRegionInvalidCountryCode:
      title: Invalid country code
      type: object
      properties:
        error:
          type: string
          description: Invalid code of the country
          example: The countryCode must have 3 characters
    ErrorRegionInvalidId:
      title: Invalid id
      type: object
      properties:
        error:
          type: string
          description: Invalid id of region
          example: Invalid id of region
    ErrorRegionNotFound:
      title: Region not found
      type: object
      properties:
        error:
          type: string
          description: Description of the error
          example: Region not found
    Commune:
      title: Commune
      type: object
      properties:
        id:
          type: number
          description: Id of the commune in database
          example: 295
        name:
          type: string
          description: Name of the commune in database
          example: Santiago
        regionId:
          type: number
          description: Id of the parent region in database
          example: 2824
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    ErrorCommuneInvalidRegionCode:
      title: Invalid region code
      type: object
      properties:
        error:
          type: string
          description: Invalid code of the region
          example: You must provide a regionCode in query params
    ErrorCommuneInvalidId:
      title: Invalid id
      type: object
      properties:
        error:
          type: string
          description: Invalid id of commune
          example: Invalid id of commune
    ErrorCommuneNotFound:
      title: Commune not found
      type: object
      properties:
        error:
          type: string
          description: Commune not found
          example: Commune not found
    City:
      title: City
      type: object
      properties:
        id:
          type: number
          description: Id of the city in database
          example: 19111
        name:
          type: string
          description: Name of the city in database
          example: Santiago
        communeId:
          type: number
          description: Id of the parent commune in database
          example: 295
        regionId:
          type: number
          description: Id of the parent region in database
          example: 2824
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    ErrorCityInvalidCommuneCode:
      title: Invalid commune code
      type: object
      properties:
        error:
          type: string
          description: Invalid code of the commune
          example: You must provide a communeCode in query params
    ErrorCityInvalidId:
      title: Invalid id
      type: object
      properties:
        error:
          type: string
          description: Invalid id of city
          example: Invalid id of city
    ErrorCityNotFound:
      title: City not found
      type: object
      properties:
        error:
          type: string
          description: City not found
          example: City not found
    ErrorFileBadRequest:
      title: Bad request
      type: object
      properties:
        error:
          type: string
          description: Error message from the API
          example: File can't be empty
    ErrorFileInvalidUuid:
      title: Invalid UUID
      type: object
      properties:
        error:
          type: string
          description: Invalid UUID of file
          example: Invalid UUID of file
    ErrorFileNotFound:
      title: File not found
      type: object
      properties:
        error:
          type: string
          description: File not found
          example: File not found
    ErrorUnauthorized:
      title: Unauthorized
      type: object
      properties:
        error:
          type: string
          description: Token is invalid or expired
          example: Token is invalid or expired
    ErrorUnavailable:
      title: Service unavailable
      type: object
      properties:
        error:
          type: string
          description: Service unavailable
          example: Service unavailable
    ErrorTimeout:
      title: Gateway timeout
      type: object
      properties:
        error:
          type: string
          description: Gateway timeout
          example: Gateway timeout
