openapi: 3.0.0
info:
  version: 1.0.0
  title: ArcoPrime PIM project API/endpoints
  description: Api for common stuff
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: API Support
    email: contacto@arcoprime.cl
    url: 'https://arcoprime.cl/'
  x-logo:
    url: 'https://www.prontocopec.cl/pronto/site/artic/20170516/imag/foto_0000000320170516112513.png'
    altText: Pronto Copec
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
servers:
  - url: 'http://localhost:3000'
tags:
  - name: geography
    description: 'Operations about geography functionalities just like countries, regions, cities and communes info'
  - name: files
    description: 'Operations about files functionalities just like upload, download or update a file'
  - name: users
    description: Operations about system users
  - name: supplier
    description: Operations about suppliers
  - name: product
    description: Operations about products
x-tagGroups:
  - name: General
    tags:
      - supplier
      - product
  - name: File management
    tags:
      - files
  - name: Geo management
    tags:
      - geography
  - name: System management
    tags:
      - users
paths:
  /helpers/country:
    get:
      tags:
        - geography
      summary: Get countries
      description: Returns a list of country
      operationId: get-helpers-country
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Country'
  '/helpers/country/{id}':
    get:
      tags:
        - geography
      summary: Get one country
      description: Returns a single country
      operationId: get-helpers-one-country
      parameters:
        - name: id
          in: path
          description: ID of country to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CountryDetail'
        '400':
          description: Invalid ID supplied
        '404':
          description: Country not found
  /helpers/region:
    get:
      tags:
        - geography
      summary: Get regions
      description: Returns all the regions of one country
      operationId: get-helpers-region
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Region'
        '400':
          description: Invalid country code
      parameters:
        - schema:
            type: string
            example: CHL
          in: query
          name: countryCode
  '/helpers/region/{id}':
    get:
      tags:
        - geography
      summary: Get one region
      description: Returns a single region
      operationId: get-helpers-one-region
      parameters:
        - name: id
          in: path
          description: ID of region to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Region'
        '400':
          description: Invalid ID supplied
        '404':
          description: Region not found
  /helpers/commune:
    get:
      tags:
        - geography
      summary: Get communes
      description: Returns all the communes of one region
      operationId: get-helpers-commune
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Commune'
        '400':
          description: Invalid region code
      parameters:
        - schema:
            type: number
            example: 2824
          in: query
          name: regionCode
  '/helpers/commune/{id}':
    get:
      tags:
        - geography
      summary: Get one commune
      description: Returns a single commune
      operationId: get-helpers-one-commune
      parameters:
        - name: id
          in: path
          description: ID of commune to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Commune'
        '400':
          description: Invalid ID supplied
        '404':
          description: Commune not found
  /helpers/city:
    get:
      tags:
        - geography
      summary: Get cities
      description: Returns all the cities of one commune
      operationId: get-helpers-city
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/City'
        '400':
          description: Invalid commune code
      parameters:
        - schema:
            type: number
            example: 295
          in: query
          name: communeCode
  '/helpers/city/{id}':
    get:
      tags:
        - geography
      summary: Get one city
      description: Returns a single city
      operationId: get-helpers-one-city
      parameters:
        - name: id
          in: path
          description: ID of city to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/City'
        '400':
          description: Invalid ID supplied
        '404':
          description: City not found
  '/helpers/file/{uuid}':
    get:
      tags:
        - files
      summary: Get a file
      description: Returns a uploaded file
      operationId: get-uploaded-file
      parameters:
        - name: uuid
          in: path
          description: UUID of file to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid UUID supplied
        '401':
          description: Unauthorized
        '404':
          description: File not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '503':
          description: Service unavailable
        '504':
          description: Gateway timeout
    delete:
      tags:
        - files
      summary: Delete a file
      description: Delete a uploaded file
      operationId: delete-uploaded-file
      parameters:
        - name: uuid
          in: path
          description: UUID of file to delete
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid UUID supplied
        '404':
          description: File not found
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /helpers/file:
    post:
      tags:
        - files
      summary: Upload a file
      description: Upload a file to the bucket
      operationId: post-upload-file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                domain:
                  type: string
                content:
                  type: string
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: string
                    example: cacf2e09-9647-4f84-9d5e-5ddcb37d4cc0
                    description: UUID del archivo
                    format: uuid
                required:
                  - code
        '400':
          description: Bad Request
components:
  schemas:
    Country:
      title: Country
      type: object
      properties:
        id:
          type: number
          description: Id of the country in database
          example: 44
        name:
          type: string
          description: Full country name in spanish language
          example: Chile
        code:
          type: string
          description: ISO standard 3166-1 alfa-3
          example: CHL
        phonePrefix:
          type: string
          description: International phone code of the country
          example: '+56'
    CountryDetail:
      title: Country
      type: object
      properties:
        id:
          type: number
          description: Id of the country in database
          example: 44
        name:
          type: string
          description: Full country name in spanish language
          example: Chile
        nameEn:
          type: string
          description: Full country name in english language
          example: Chile
        code:
          type: string
          description: ISO standard 3166-1 alfa-3
          example: CHL
        phonePrefix:
          type: string
          description: International phone code of the country
          example: '+56'
    Region:
      title: Region
      type: object
      properties:
        id:
          type: number
          description: Id of the region in database
          example: 2824
        name:
          type: string
          description: Name of the region in database
          example: Región Metropolitana de Santiago
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    Commune:
      title: Commune
      type: object
      properties:
        id:
          type: number
          description: Id of the commune in database
          example: 295
        name:
          type: string
          description: Name of the commune in database
          example: Santiago
        regionId:
          type: number
          description: Id of the parent region in database
          example: 2824
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    City:
      title: City
      type: object
      properties:
        id:
          type: number
          description: Id of the city in database
          example: 19111
        name:
          type: string
          description: Name of the city in database
          example: Santiago
        communeId:
          type: number
          description: Id of the parent commune in database
          example: 295
        regionId:
          type: number
          description: Id of the parent region in database
          example: 2824
        countryId:
          type: number
          description: Id of the parent country in database
          example: 44
    Error:
      title: Error
      type: object
      properties:
        userMessage:
          type: string
        internalException:
          type: string
