openapi: 3.1.0
info:
  title: product-api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /product:
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  pageMeta:
                    $ref: '#/components/schemas/PageMeta'
      operationId: get-product
      parameters:
        - schema:
            type: number
          in: query
          name: page
          description: page number
          required: true
        - schema:
            type: number
            default: 10
          in: query
          name: take
          description: number of files per page
  /classification:
    get:
      summary: Your GET endpoint
      tags: []
      responses: {}
      operationId: get-classification
      parameters:
        - schema:
            type: number
            example: 2
          in: query
          name: level
          required: true
        - schema:
            type: string
            example: A0101
          in: query
          name: parentLevelId
components:
  schemas:
    Product:
      title: Product
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        sku:
          type: string
        genericName:
          type: string
          minLength: 1
          maxLength: 15
        brandName:
          type: string
          format: email
        clasification:
          $ref: '#/components/schemas/Clasification'
        type:
          type: string
          description: Set to true if the user's email has been verified.
          enum:
            - MERCADERIA
        creationStatus:
          type: string
          format: date
          description: The date that the user was created.
          enum:
            - EDITING
            - REVIEW
            - TO_BE_APPROVED
            - TO_BE_PUBLISHED
            - PUBLISHED
            - REJECTED
            - ERROR
        log:
          $ref: '#/components/schemas/Log'
        photoUrl:
          type: string
          format: uuid
    Clasification:
      title: Clasification
      type: object
      properties:
        category:
          type: string
        hierarchy:
          type: string
        family:
          type: string
    Log:
      title: Log
      type: object
      description: Model to support logging information
      properties:
        createdAt:
          type: string
          format: date-time
          example: '2018-05-15T14:51:12.402+00:00'
        updatedAt:
          type: string
          format: date-time
          example: '2018-05-15T14:51:12.402+00:00'
        createdBy:
          $ref: '#/components/schemas/User'
        updatedBy:
          $ref: '#/components/schemas/User'
    Error:
      title: Error
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    PageMeta:
      title: PageMeta
      type: object
      description: pagination data
      properties:
        page:
          type: number
          description: current page
        take:
          type: number
          description: number of rows per page
        totalRecords:
          type: number
          description: total number of records
        pageCount:
          type: number
          description: total number of pages
        hasPreviusPage:
          type: boolean
          description: this flag means there is a previous page to retrieve
        hasNextPage:
          type: boolean
          description: this flag means there is a next page to retrieve
    User:
      title: User
      type: object
      properties:
        id:
          type: number
        name:
          type: string
        lastname:
          type: string
        email:
          type: string
