openapi: 3.1.0
info:
  title: supplier-api
  version: '1.0'
  description: API de proveedores
  contact:
    name: Arcoprime
  summary: API de proveedores
servers:
  - url: 'http://localhost:3000'
paths:
  '/supplier/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
    get:
      summary: Get Supplier Info by Supplier ID
      tags:
        - supplier
      responses:
        '200':
          description: Supplier Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Supplier'
      operationId: get-supplier-supplierID
      description: Retrieve the information of the supplier with the matching supplier ID.
      parameters:
        - schema:
            type: string
          in: query
          name: rut
          description: RUT del proveedor
  /supplier:
    post:
      summary: Create Supplier
      tags:
        - supplier
      operationId: post-supplier
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                type: 'null'
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
            examples: {}
        description: Post the necessary fields for the API to create a new supplier.
      description: Create a new supplier.
    parameters: []
  /supplier/document:
    parameters: []
    post:
      summary: Upload document
      operationId: post-supplier-id-doc
      responses:
        '200':
          description: OK
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Document'
          application/json:
            schema:
              type: object
              properties: {}
          application/xml:
            schema:
              type: object
              properties: {}
      description: Endpoint to send a file and its metadata
components:
  schemas:
    Supplier:
      title: Supplier
      type: object
      description: Modelo del proveedor
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        name:
          type: string
        fictionName:
          type: string
        personType:
          type: string
          enum:
            - Natural
            - Jurídica
        origin:
          type: string
          enum:
            - Nacional
            - Internacional
        sapCode:
          type: string
        status:
          type: string
          enum:
            - NEW
            - APPROVED
            - REJECTED
            - PENDING
            - REGISTERING
            - READY
            - ERROR
        rut:
          type: string
        address:
          $ref: '#/components/schemas/Address'
        legalAgent:
          $ref: '#/components/schemas/Contact'
        purchaseOrderContact:
          $ref: '#/components/schemas/Contact'
        entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        statusLog:
          type: array
          items:
            $ref: '#/components/schemas/StatusLog'
        accountGroup:
          type: string
          enum:
            - DIST
            - ACREE
        treasuryGroup:
          type: string
          enum:
            - GASTO
            - EXISTENCIA
      required:
        - name
        - rut
    Address:
      title: Address
      type: object
      properties:
        id:
          type: number
        country:
          type: string
          example: Segun estandar ISO
        region:
          type: string
        city:
          type: string
        commune:
          type: string
        street:
          type: string
        zipCode:
          type: string
    Payment:
      title: Payment
      type: object
      properties:
        currencyCod:
          type: string
          enum:
            - PEN
            - CLP
            - USD
            - ARS
            - EUR
        condition:
          type: string
          enum:
            - 30_DAYS
            - 15_DAYS
        supplierId:
          type: number
    Contact:
      title: Contact
      type: object
      properties:
        id:
          type: number
        names:
          type: string
        lastnames:
          type: string
        rut:
          type: string
        email:
          type: string
        phone:
          type: string
        language:
          type: string
          enum:
            - ESP
        businessArea:
          type: string
        jobTitle:
          type: string
    Entity:
      title: Entity
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    StatusLog:
      title: StatusLog
      type: object
      properties:
        id:
          type: string
          example: UUID
        username:
          type: string
        timestamp:
          type: string
        newStatus:
          type: string
        oldStatus:
          type: string
    Document:
      title: Document
      type: object
      properties:
        id:
          type: string
          example: UUID
        type:
          type: string
          enum:
            - ROL
            - EVIDENCIA
        originalFilename:
          type: string
        format:
          type: string
          enum:
            - PNG
            - JPG
            - PDF
        status:
          type: string
        timestamp:
          type: string
        idSupplier:
          type: number
        file:
          type: string
          format: binary
    EntitySupplier:
      title: EntitySupplier
      type: object
      properties:
        entityId:
          type: number
        supplierid:
          type: number
        invoiceIssuer:
          type: number
        status:
          type: string
  securitySchemes: {}
tags:
  - name: supplier
